import type { WordPair, WordPairDifficulty } from './types'
import { withWordPairDefaults } from './wordPairOps'

const difficultyByLabel: Record<string, WordPairDifficulty> = {
  '吃的': 'easy',
  '喝的': 'easy',
  '水果': 'easy',
  '数码': 'medium',
  'App': 'medium',
  '互联网': 'hard',
  '科技': 'hard',
  '娱乐': 'medium',
  '运动': 'medium',
  '自然': 'easy',
  '职业': 'medium',
  '动物': 'easy',
  '生活': 'medium',
  '出行': 'medium',
  '工作': 'hard',
  '文具': 'easy',
  '地点': 'medium',
  '艺术': 'medium',
  '历史': 'hard',
  '校园': 'medium',
  '商业': 'hard',
}

const qualityScoreOverrides: Record<string, number> = {
  'b-12': 70,
  'b-18': 68,
  'b-19': 48,
  'b-20': 42,
  'b-24': 64,
  'b-32': 66,
  'b-36': 68,
  'b-37': 65,
  'b-49': 46,
  'b-50': 67,
}

const difficultyOverrides: Record<string, WordPairDifficulty> = {
  'b-12': 'hard',
  'b-19': 'hard',
  'b-20': 'hard',
  'b-24': 'hard',
  'b-32': 'medium',
  'b-49': 'hard',
  'b-65': 'medium',
  'b-69': 'hard',
  'b-75': 'medium',
  'b-79': 'medium',
  'b-80': 'medium',
  'b-81': 'hard',
  'b-83': 'easy',
  'b-88': 'hard',
  'b-89': 'hard',
  'b-95': 'hard',
  'b-96': 'easy',
  'b-97': 'easy',
  'b-99': 'easy',
  'b-104': 'medium',
  'b-106': 'medium',
  'b-107': 'medium',
  'b-109': 'medium',
  'b-110': 'medium',
  'b-111': 'medium',
  'b-112': 'hard',
  'b-113': 'medium',
  'b-114': 'easy',
  'b-115': 'medium',
  'b-116': 'hard',
  'b-117': 'medium',
  'b-118': 'medium',
  'b-119': 'medium',
  'b-120': 'medium',
}

const disabledIds = new Set(['b-19', 'b-20', 'b-49'])

export const builtinWordPairs: WordPair[] = [
  { id: 'b-01', civilian: '火锅', undercover: '麻辣烫', label: '吃的' },
  { id: 'b-02', civilian: '奶茶', undercover: '咖啡', label: '喝的' },
  { id: 'b-03', civilian: '汉堡', undercover: '三明治', label: '吃的' },
  { id: 'b-04', civilian: '饺子', undercover: '馄饨', label: '吃的' },
  { id: 'b-05', civilian: '烧烤', undercover: '炸串', label: '吃的' },
  { id: 'b-06', civilian: '披萨', undercover: '意面', label: '吃的' },
  { id: 'b-07', civilian: '米饭', undercover: '面条', label: '吃的' },
  { id: 'b-08', civilian: '可乐', undercover: '雪碧', label: '喝的' },
  { id: 'b-09', civilian: '橙汁', undercover: '柠檬水', label: '喝的' },
  { id: 'b-10', civilian: '苹果', undercover: '梨', label: '水果' },

  { id: 'b-11', civilian: '手机', undercover: '平板', label: '数码' },
  { id: 'b-12', civilian: '电脑', undercover: '笔记本', label: '数码' },
  { id: 'b-13', civilian: '耳机', undercover: '音箱', label: '数码' },
  { id: 'b-14', civilian: '相机', undercover: '摄像机', label: '数码' },
  { id: 'b-15', civilian: '微信', undercover: 'QQ', label: 'App' },
  { id: 'b-16', civilian: '抖音', undercover: '快手', label: 'App' },
  { id: 'b-17', civilian: '微博', undercover: '小红书', label: 'App' },
  { id: 'b-18', civilian: '淘宝', undercover: '京东', label: 'App' },
  { id: 'b-19', civilian: '地图', undercover: '导航', label: 'App' },
  { id: 'b-20', civilian: '浏览器', undercover: '搜索引擎', label: '互联网' },

  { id: 'b-21', civilian: '电影', undercover: '电视剧', label: '娱乐' },
  { id: 'b-22', civilian: '综艺', undercover: '纪录片', label: '娱乐' },
  { id: 'b-23', civilian: '小说', undercover: '漫画', label: '娱乐' },
  { id: 'b-24', civilian: 'KTV', undercover: '酒吧', label: '娱乐' },
  { id: 'b-25', civilian: '音乐会', undercover: '演唱会', label: '娱乐' },

  { id: 'b-26', civilian: '足球', undercover: '篮球', label: '运动' },
  { id: 'b-27', civilian: '羽毛球', undercover: '乒乓球', label: '运动' },
  { id: 'b-28', civilian: '跑步', undercover: '健走', label: '运动' },
  { id: 'b-29', civilian: '瑜伽', undercover: '普拉提', label: '运动' },
  { id: 'b-30', civilian: '游泳', undercover: '冲浪', label: '运动' },

  { id: 'b-31', civilian: '春天', undercover: '秋天', label: '自然' },
  { id: 'b-32', civilian: '太阳', undercover: '月亮', label: '自然' },
  { id: 'b-33', civilian: '大海', undercover: '湖泊', label: '自然' },
  { id: 'b-34', civilian: '山', undercover: '丘陵', label: '自然' },
  { id: 'b-35', civilian: '雨', undercover: '雪', label: '自然' },

  { id: 'b-36', civilian: '老师', undercover: '教练', label: '职业' },
  { id: 'b-37', civilian: '医生', undercover: '护士', label: '职业' },
  { id: 'b-38', civilian: '程序员', undercover: '产品经理', label: '职业' },
  { id: 'b-39', civilian: '设计师', undercover: '摄影师', label: '职业' },
  { id: 'b-40', civilian: '律师', undercover: '法官', label: '职业' },

  { id: 'b-41', civilian: '猫', undercover: '狗', label: '动物' },
  { id: 'b-42', civilian: '兔子', undercover: '仓鼠', label: '动物' },
  { id: 'b-43', civilian: '鲸鱼', undercover: '海豚', label: '动物' },
  { id: 'b-44', civilian: '老虎', undercover: '狮子', label: '动物' },
  { id: 'b-45', civilian: '企鹅', undercover: '海豹', label: '动物' },

  { id: 'b-46', civilian: '早起', undercover: '熬夜', label: '生活' },
  { id: 'b-47', civilian: '地铁', undercover: '公交', label: '出行' },
  { id: 'b-48', civilian: '打车', undercover: '自驾', label: '出行' },
  { id: 'b-49', civilian: '现金', undercover: '移动支付', label: '生活' },
  { id: 'b-50', civilian: '会议', undercover: '讨论', label: '工作' },

  { id: 'b-51', civilian: '夏天', undercover: '冬天', label: '自然' },
  { id: 'b-52', civilian: '电梯', undercover: '楼梯', label: '生活' },
  { id: 'b-53', civilian: '口罩', undercover: '围巾', label: '生活' },
  { id: 'b-54', civilian: '铅笔', undercover: '圆珠笔', label: '文具' },
  { id: 'b-55', civilian: '橡皮', undercover: '修正带', label: '文具' },
  { id: 'b-56', civilian: '书店', undercover: '图书馆', label: '地点' },
  { id: 'b-57', civilian: '超市', undercover: '便利店', label: '地点' },
  { id: 'b-58', civilian: '公园', undercover: '广场', label: '地点' },
  { id: 'b-59', civilian: '高铁', undercover: '飞机', label: '出行' },
  { id: 'b-60', civilian: '雨伞', undercover: '雨衣', label: '生活' },

  { id: 'b-61', civilian: '寿司', undercover: '刺身', label: '吃的' },
  { id: 'b-62', civilian: '拉面', undercover: '乌冬面', label: '吃的' },
  { id: 'b-63', civilian: '慕斯', undercover: '布丁', label: '吃的' },
  { id: 'b-64', civilian: '酸奶', undercover: '奶昔', label: '喝的' },
  { id: 'b-65', civilian: '榴莲', undercover: '菠萝蜜', label: '水果' },
  { id: 'b-66', civilian: '葡萄', undercover: '蓝莓', label: '水果' },
  { id: 'b-67', civilian: '智能手表', undercover: '手环', label: '数码' },
  { id: 'b-68', civilian: '投影仪', undercover: '电视', label: '数码' },
  { id: 'b-69', civilian: '单反', undercover: '微单', label: '数码' },
  { id: 'b-70', civilian: '无人机', undercover: '遥控飞机', label: '数码' },

  { id: 'b-71', civilian: 'B站', undercover: '知乎', label: 'App' },
  { id: 'b-72', civilian: '美团', undercover: '饿了么', label: 'App' },
  { id: 'b-73', civilian: '网易云音乐', undercover: 'QQ音乐', label: 'App' },
  { id: 'b-74', civilian: '支付宝', undercover: '微信支付', label: 'App' },
  { id: 'b-75', civilian: '云盘', undercover: '网盘', label: '互联网' },
  { id: 'b-76', civilian: '验证码', undercover: '口令', label: '互联网' },
  { id: 'b-77', civilian: '算法', undercover: '模型', label: '科技' },
  { id: 'b-78', civilian: '数据库', undercover: '缓存', label: '科技' },
  { id: 'b-79', civilian: '芯片', undercover: '处理器', label: '科技' },
  { id: 'b-80', civilian: '直播', undercover: '录播', label: '互联网' },

  { id: 'b-81', civilian: '话剧', undercover: '歌剧', label: '艺术' },
  { id: 'b-82', civilian: '素描', undercover: '油画', label: '艺术' },
  { id: 'b-83', civilian: '雕塑', undercover: '手办', label: '艺术' },
  { id: 'b-84', civilian: '朝代', undercover: '年代', label: '历史' },
  { id: 'b-85', civilian: '甲骨文', undercover: '金文', label: '历史' },
  { id: 'b-86', civilian: '诸侯', undercover: '藩王', label: '历史' },
  { id: 'b-87', civilian: '桌游', undercover: '剧本杀', label: '娱乐' },
  { id: 'b-88', civilian: '票房', undercover: '收视率', label: '娱乐' },
  { id: 'b-89', civilian: '马拉松', undercover: '铁人三项', label: '运动' },
  { id: 'b-90', civilian: '攀岩', undercover: '蹦极', label: '运动' },

  { id: 'b-91', civilian: '击剑', undercover: '射箭', label: '运动' },
  { id: 'b-92', civilian: '博物馆', undercover: '美术馆', label: '地点' },
  { id: 'b-93', civilian: '动物园', undercover: '海洋馆', label: '地点' },
  { id: 'b-94', civilian: '班主任', undercover: '辅导员', label: '校园' },
  { id: 'b-95', civilian: '奖学金', undercover: '助学金', label: '校园' },
  { id: 'b-96', civilian: '期中考', undercover: '期末考', label: '校园' },
  { id: 'b-97', civilian: '学士', undercover: '硕士', label: '校园' },
  { id: 'b-98', civilian: '创业', undercover: '融资', label: '商业' },
  { id: 'b-99', civilian: '股票', undercover: '基金', label: '商业' },
  { id: 'b-100', civilian: '估值', undercover: '市值', label: '商业' },

  { id: 'b-101', civilian: '供应链', undercover: '产业链', label: '商业' },
  { id: 'b-102', civilian: '合伙人', undercover: '股东', label: '商业' },
  { id: 'b-103', civilian: 'KPI', undercover: 'OKR', label: '工作' },
  { id: 'b-104', civilian: '简历', undercover: '作品集', label: '工作' },
  { id: 'b-105', civilian: '面试', undercover: '答辩', label: '工作' },
  { id: 'b-106', civilian: '甲方', undercover: '乙方', label: '工作' },
  { id: 'b-107', civilian: '通勤', undercover: '出差', label: '出行' },
  { id: 'b-108', civilian: '雾', undercover: '霾', label: '自然' },
  { id: 'b-109', civilian: '雷阵雨', undercover: '暴雨', label: '自然' },
  { id: 'b-110', civilian: '潮汐', undercover: '洋流', label: '自然' },

  { id: 'b-111', civilian: '极光', undercover: '流星雨', label: '自然' },
  { id: 'b-112', civilian: '羊驼', undercover: '骆驼', label: '动物' },
  { id: 'b-113', civilian: '北极熊', undercover: '棕熊', label: '动物' },
  { id: 'b-114', civilian: '古琴', undercover: '古筝', label: '艺术' },
  { id: 'b-115', civilian: '脱口秀', undercover: '相声', label: '娱乐' },
  { id: 'b-116', civilian: '纪录片', undercover: '访谈节目', label: '娱乐' },
  { id: 'b-117', civilian: '小说改编', undercover: '真实事件', label: '娱乐' },
  { id: 'b-118', civilian: '海报', undercover: '传单', label: '艺术' },
  { id: 'b-119', civilian: '电吉他', undercover: '贝斯', label: '艺术' },
  { id: 'b-120', civilian: '显微镜', undercover: '望远镜', label: '科技' },
].map((pair) =>
  withWordPairDefaults({
    ...pair,
    source: 'builtin',
    tags: pair.label ? [pair.label] : [],
    difficulty: difficultyOverrides[pair.id] ?? difficultyByLabel[pair.label ?? ''] ?? 'medium',
    qualityScore: qualityScoreOverrides[pair.id] ?? 80,
    status: disabledIds.has(pair.id) ? 'disabled' : 'active',
    cooldownRounds: 5,
  }),
)
